[package]
name = "CLI_password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.1"
argon2 = "0.5.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
rand = "0.8.5"
anyhow = "1.0"  # Add this line